name: Deploy tag â†’ gh-pages/tag

on:
  push:
    tags:
      - '*'            # Trigger on any tag push
  workflow_dispatch:   # Manual trigger

permissions: write-all

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup repo ğŸ”§
        uses: ./.github/actions

      - name: Build site
        env:
          BASE_PATH: ""
        run: pnpm buildRepo

      - name: Deploying release ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          target-folder: ${{ github.ref_name }}
          clean: false

      - name: Release notes ğŸ“
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release ğŸš€
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false       # <-- ensures release is published
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}